# Stage 1: Data Preparation <a class="anchor" id="top"></a>

### Problem Statement: Given a particular flight, is there going to be a flight delay or not? (Yes/No)
### Problem Type: Classification

### Navigation
> ### [1. Deparature Delay Dataset](#first-bullet)
> ### [2. Weather Events Dataset](#second-bullet)
> ### [3. IATA Codes Dataset](#third-bullet)
> ### [4. Data Summary](#fourth-bullet)

### Required Files

> Departure Delay Dataset: `dataset.csv`    
> Weather Events Dataset: `WeatherEvents_Jan2016-2022.csv`   
> IATA Code: `iata-icao.csv`

In [25]:
import pandas as pd

## 1. Departure Delay Dataset <a class="anchor" id="first-bullet"></a>
Dataset from Kaggle: **"Flight Status Prediction"** by *Rob Mulla*  
Source: https://www.kaggle.com/datasets/robikscube/flight-delay-dataset-20182022/data  
For this project, we are only using data from **2022 July**!

### Import CSV file into a DataFrame

In [26]:
flights_original = pd.read_csv('data/dataset.csv', low_memory = False) # Importing 2022 July dataset
flights_original.head()

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,...,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum,Duplicate,Unnamed: 119
0,2022,3,7,19,2,2022-07-19,AA,AA_CODESHARE,19805,AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
1,2022,3,7,20,3,2022-07-20,AA,AA_CODESHARE,19805,AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
2,2022,3,7,21,4,2022-07-21,AA,AA_CODESHARE,19805,AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
3,2022,3,7,24,7,2022-07-24,AA,AA_CODESHARE,19805,AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
4,2022,3,7,25,1,2022-07-25,AA,AA_CODESHARE,19805,AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN

In [27]:
# Print column information
for column in flights_original.columns:
    print(f"{column}: {flights_original[column].dtype}")

Year: int64
Quarter: int64
Month: int64
DayofMonth: int64
DayOfWeek: int64
FlightDate: object
Marketing_Airline_Network: object
Operated_or_Branded_Code_Share_Partners: object
DOT_ID_Marketing_Airline: int64
IATA_Code_Marketing_Airline: object
Flight_Number_Marketing_Airline: int64
Originally_Scheduled_Code_Share_Airline: object
DOT_ID_Originally_Scheduled_Code_Share_Airline: float64
IATA_Code_Originally_Scheduled_Code_Share_Airline: object
Flight_Num_Originally_Scheduled_Code_Share_Airline: float64
Operating_Airline : object
DOT_ID_Operating_Airline: int64
IATA_Code_Operating_Airline: object
Tail_Number: object
Flight_Number_Operating_Airline: int64
OriginAirportID: int64
OriginAirportSeqID: int64
OriginCityMarketID: int64
Origin: object
OriginCityName: object
OriginState: object
OriginStateFips: int64
OriginStateName: object
OriginWac: int64
DestAirportID: int64
DestAirportSeqID: int64
DestCityMarketID: int64
Dest: object
DestCityName: object
DestState: object
DestStateFips: int64
DestStateName: object
DestWac: int64
CRSDepTime: int64
DepTime: float64
DepDelay: float64
DepDelayMinutes: float64
DepDel15: float64
DepartureDelayGroups: float64
DepTimeBlk: object
TaxiOut: float64
WheelsOff: float64
WheelsOn: float64
TaxiIn: float64
CRSArrTime: int64
ArrTime: float64
ArrDelay: float64
ArrDelayMinutes: float64
ArrDel15: float64
ArrivalDelayGroups: float64
ArrTimeBlk: object
Cancelled: float64
CancellationCode: object
Diverted: float64
CRSElapsedTime: float64
ActualElapsedTime: float64
AirTime: float64
Flights: float64
Distance: float64
DistanceGroup: int64
CarrierDelay: float64
WeatherDelay: float64
NASDelay: float64
SecurityDelay: float64
LateAircraftDelay: float64
FirstDepTime: float64
TotalAddGTime: float64
LongestAddGTime: float64
DivAirportLandings: int64
DivReachedDest: float64
DivActualElapsedTime: float64
DivArrDelay: float64
DivDistance: float64
Div1Airport: object
Div1AirportID: float64
Div1AirportSeqID: float64
Div1WheelsOn: float64
Div1TotalGTime: float64
Div1LongestGTime: float64
Div1WheelsOff: float64
Div1TailNum: object
Div2Airport: object
Div2AirportID: float64
Div2AirportSeqID: float64
Div2WheelsOn: float64
Div2TotalGTime: float64
Div2LongestGTime: float64
Div2WheelsOff: float64
Div2TailNum: object
Div3Airport: float64
Div3AirportID: float64
Div3AirportSeqID: float64
Div3WheelsOn: float64
Div3TotalGTime: float64
Div3LongestGTime: float64
Div3WheelsOff: float64
Div3TailNum: float64
Div4Airport: float64
Div4AirportID: float64
Div4AirportSeqID: float64
Div4WheelsOn: float64
Div4TotalGTime: float64
Div4LongestGTime: float64
Div4WheelsOff: float64
Div4TailNum: float64
Div5Airport: float64
Div5AirportID: float64
Div5AirportSeqID: float64
Div5WheelsOn: float64
Div5TotalGTime: float64
Div5LongestGTime: float64
Div5WheelsOff: float64
Div5TailNum: float64
Duplicate: object
Unnamed: 119: float64

###  Cleaning Column Names

In [28]:
# Removing Whitespaces
flights_original.columns = flights_original.columns.str.strip()

# Renaming "DayofMonth" and "Operating_Airline" for consistency
flights_original = flights_original.rename(columns={"DayofMonth" : "DayOfMonth", "Operating_Airline": "OperatingAirline"})

### Removing Cancelled Flights and Cleaning NaN values

In [29]:
# Removing Cancelled FLights
flights_original = flights_original.drop(flights_original[(flights_original.Cancelled == 1)].index)

# Dropping Cancelled Column
flights_original = flights_original.drop('Cancelled', axis=1)
print("Data dimensions : ", flights_original.shape)

Data dimensions :  (607657, 119)

In [30]:
# Removing NaN values if any
flights_original.dropna(inplace=True, axis=1)
print("Data dimensions: ", flights_original.shape)

Data dimensions:  (607657, 52)

In [31]:
# Select only the desired columns
flights_df = pd.DataFrame(flights_original[[
                    'Month',
                    'DayOfMonth',
                    'DayOfWeek',
                    'FlightDate',
                    'OperatingAirline',
                    'Origin',
                    'OriginState',
                    'OriginAirportID',
                    'Dest',
                    'DestState',
                    'DestAirportID',
                    'CRSDepTime',
                    'DepDelay',
                    'DepDelayMinutes',
                    'DepDel15',
                    'TaxiOut',
                    'Distance',
                    'DistanceGroup'
                ]])

## 2. Weather Events Dataset <a class="anchor" id="second-bullet"></a>
Dataset from Kaggle: **"US Weather Events (2016 - 2022)"** by *Sobhan Moosavi*  
Source: https://www.kaggle.com/datasets/sobhanmoosavi/us-weather-events

<div class="alert alert-block alert-danger">
<b>Note:</b> The weather events dataset has been excluded in the GitHub repository as it was too large and was only used in analysis, not training.
</div>

Our group wanted to augment the flight dataset with this dataset to consider the factor of weather events causing a departure delay to flights and we chose to insert a column that indicated whether or not there was severe weather during the departure time of the flight.

In [32]:
weather = pd.read_csv("data/WeatherEvents_Jan2016-Dec2022.csv")
weather.head()

,EventId,Type,Severity,StartTime(UTC),EndTime(UTC),Precipitation(in),TimeZone,AirportCode,LocationLat,LocationLng,City,County,State,ZipCode
0,W-1,Snow,Light,2016-01-06 23:14:00,2016-01-07 00:34:00,0.00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0
1,W-2,Snow,Light,2016-01-07 04:14:00,2016-01-07 04:54:00,0.00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0
2,W-3,Snow,Light,2016-01-07 05:54:00,2016-01-07 15:34:00,0.03,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0
3,W-4,Snow,Light,2016-01-08 05:34:00,2016-01-08 05:54:00,0.00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0
4,W-5,Snow,Light,2016-01-08 13:54:00,2016-01-08 15:54:00,0.00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0

In [33]:
from datetime import datetime
from dateutil import parser

In [34]:
# Extracting July 2022 data
# Example date: "2016-01-07 00:34:00"
def extract_month_year(row):
    parsed = parser.parse(row["StartTime(UTC)"])
    return str(parsed.month) +  "-" + str(parsed.year)

weather['Month-Year'] = weather.apply(extract_month_year, axis=1)
weather_2021 = weather[weather['Month-Year'] == "7-2022"]

In [35]:
# Prune for only severe or other severity (All "Other" severity indicates hail, and all hail has "Other" severity)
severe_weather = weather_2021.query("Severity == 'Severe' or Severity == 'Other'")

## 3. IATA Codes Dataset <a class="anchor" id="third-bullet"></a>
Dataset from Github: **"IATA/ICAO List"** by *IP2Location*  
Source: https://github.com/ip2location/ip2location-iata-icao

<div class="alert alert-block alert-danger">
<b>Note:</b> The IATA codes dataset has been excluded in the GitHub repository as it was only used in analysis, not training.
</div>

We had to use another source that would help consolidate all airport codes to one type so that we could compare between data sets.

In [36]:
# Create a dictionary that will speed up this search process
iata_icao = pd.read_csv("data/iata-icao.csv")
iata_to_icao_map = iata_icao.set_index('iata')['icao'].to_dict()

# Initialize the coumn to have all zeros
flights_df["SevereWeatherEvent"] = "N"

In [37]:
icao_to_event_times = {}

for index in severe_weather.index:
    icao = severe_weather["AirportCode"][index]
    start = severe_weather["StartTime(UTC)"][index]
    end = severe_weather["EndTime(UTC)"][index]

    if icao in icao_to_event_times:
        icao_to_event_times[icao].append([start, end])
    else:
        icao_to_event_times[icao] = [[start, end]]

In [38]:
def check_event(row):
    iata = row["Origin"]

    if iata not in iata_to_icao_map:
        return "N"
    
    icao = iata_to_icao_map[iata]
    if icao not in icao_to_event_times:
        return "N"
    
    flight_date = str(row["FlightDate"])
    flight_time = str(row["CRSDepTime"]) # Format: "hhmm" or "hmm" or "mm" or "m"
    if len(flight_time) < 4:
        flight_time = "0" + flight_time
    if len(flight_time) < 4:
        flight_time = "0000"

    date_time_string = flight_date + " " + flight_time[0:2] + ":" + flight_time[2:4] + ":00"
    flight_date_time = parser.parse(date_time_string)

    events = icao_to_event_times[icao]
    for event in events:
        if flight_date_time >= parser.parse(event[0]) and flight_date_time <= parser.parse(event[1]):
            return "Y"
        
    return "N"
    

flights_df['SevereWeatherEvent'] = flights_original.apply(check_event, axis=1)
# Save our prepared data set
flights_df.to_csv('data/prepared_dataset.csv')

###  The prepared data set is now saved to 
`data/prepared_data.csv`.

## 4. Data Summary <a class="anchor" id="fourth-bullet"></a>

In [39]:
flights_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 607657 entries, 0 to 618789
Data columns (total 19 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Month               607657 non-null  int64
 1   DayOfMonth          607657 non-null  int64
 2   DayOfWeek           607657 non-null  int64
 3   FlightDate          607657 non-null  object
 4   OperatingAirline    607657 non-null  object
 5   Origin              607657 non-null  object
 6   OriginState         607657 non-null  object
 7   OriginAirportID     607657 non-null  int64
 8   Dest                607657 non-null  object
 9   DestState           607657 non-null  object
 10  DestAirportID       607657 non-null  int64
 11  CRSDepTime          607657 non-null  int64
 12  DepDelay            607657 non-null  float64
 13  DepDelayMinutes     607657 non-null  float64
 14  DepDel15            607657 non-null  float64
 15  TaxiOut             607657 non-null  float64
 16  Distance            607657 non-null  float64
 17  DistanceGroup       607657 non-null  int64
 18  SevereWeatherEvent  607657 non-null  object
dtypes: float64(5), int64(7), object(7)
memory usage: 92.7+ MB

---

<center><h3><b>Next Chapter: Exploratory Data Analysis (EDA)</b></h3></center>

<center><h3><a href="#top">Scroll To Top </a></h3></center>